id: P003186
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG8285
  title: དཔལ་སྤྲུལ་མཛད་རྣམ་ཉེར་བསྡུས།
  author: ''
  volumes:
    d85b1423e1b54147a0a1265f19c36dd9:
      image_group_id: I1KG8483
      title: ''
      volume_number: 1
      total_pages: 112
      base_file: v001.txt
